ContosoUniversity/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContosoUniversity.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

ContosoUniversity/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContosoUniversity.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

ContosoUniversity/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContosoUniversity.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ContosoUniversity/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ContosoUniversity.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace ContosoUniversity.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
            Console.WriteLine("this is in dex");
        }
    }
}

ContosoUniversity/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContosoUniversity.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly SchoolContext _schoolContext;
        public RegisterModel(SchoolContext schoolContext)
        {
            _schoolContext = schoolContext;
        }
        [BindProperty]
        public Student student { get; set; }
        [BindProperty]
        public Course course { get; set; }
        [BindProperty]
        public Enrollment enrollment { get; set; }
        [BindProperty]
        public INPUT inputtt { get; set; }

        //public enum Grade { A, B, C, D, F }

        public class INPUT 
        {
            public string FName { get; set; }
            public string LName { get; set; }
            public string Course { get; set; }
            public int Credit { get; set; }
            public DateTime EnrollmentDate { get; set; }
            public string Grade { get; set; }
        }

        public async Task<IActionResult> OnPostScheduleAsync()
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }

            Student student = (new Student
            {
                FirstMidName = inputtt.FName,
                LastName = inputtt.LName,
                EnrollmentDate = DateTime.Now,
                
            });

            Course course = (new Course
            {
                CourseID = 8907,
                Title = inputtt.Course,
            });
            Enrollment enrollment = (new Enrollment
            {
                Grade = Grade.A,
                Course = course,
                Student = student,
                StudentID = student.ID,
            });

            //enrollment.Student.FirstMidName = inputtt.FName;
            //enrollment.Student.LastName = inputtt.LName;
            //enrollment.Course.Title = inputtt.Course;
            //enrollment.Course.Credits = inputtt.Credit;
            //enrollment.Student.EnrollmentDate = DateTime.Now;
            //enrollment.Grade = Grade.A;

            //_schoolContext.Students.Add(student);
            //_schoolContext.Courses.Add(course);
            _schoolContext.Add(enrollment);
            await _schoolContext.SaveChangesAsync();
            return RedirectToPage("/Schedule");
        }
    }
}

ContosoUniversity/Pages/Schedule.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Pages
{
    public class ScheduleModel : PageModel
    {
        private readonly SchoolContext _schoolContext;
        public ScheduleModel(SchoolContext schoolContext)
        {
            _schoolContext = schoolContext;
        }

        public IList<Enrollment> enrollment { get; set; }

        public async Task OnGetAsync()
        {
            enrollment = await _schoolContext.Enrollments.ToListAsync();
        }
    }
}

ContosoUniversity/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

ContosoUniversity/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ContosoUniversity/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="jumbotron">
    <h1>Contoso University</h1>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Welcome to Contoso University</h2>
        <p>
            Contoso University is a sample application that
            demonstrates how to use Entity Framework Core in an
            ASP.NET Core MVC web application.
        </p>
    </div>
    <div class="col-md-4">
        <h2>Build it from scratch</h2>
        <p>You can build the application by following the steps in a series of tutorials.</p>
        <p><a class="btn btn-default" href="https://docs.asp.net/en/latest/data/ef-mvc/intro.html">See the tutorial &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Download it</h2>
        <p>You can download the completed project from GitHub.</p>
        <p><a class="btn btn-default" href="https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-mvc/intro/samples/cu-final">See project source code &raquo;</a></p>
    </div>
</div>

ContosoUniversity/Pages/Register.cshtml
@page
@model ContosoUniversity.Pages.RegisterModel
@{
    ViewData["Title"] = "Register";
}

<h2><b>Register</b></h2>

<form method="post">
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-2 ">
            <label asp-for="inputtt.FName" class="control-label">First Name</label>
        </div>
        <div class="col-sm-7">
            <input type="text" class="form-control" asp-for="inputtt.FName" placeholder="Nicha">
        </div>
        <div class="col-sm-2"></div>
    </div><br>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-2 ">
            <label asp-for="inputtt.LName" class="control-label">Last Name</label>
        </div>
        <div class="col-sm-7">
            <input type="text" class="form-control" asp-for="inputtt.LName" placeholder="Nina">
        </div>
        <div class="col-sm-2"></div>
    </div><br>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-2 ">
            <label asp-for="inputtt.Course" class="control-label">Course Name</label>
        </div>
        <div class="col-sm-7">
            <input type="text" class="form-control" asp-for="inputtt.Course" placeholder="ASP.NET For Beginner">
        </div>
        <div class="col-sm-2"></div>
    </div><br>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-2 ">
            <label asp-for="inputtt.Credit" class="control-label">Credit</label>
        </div>
        <div class="col-sm-7">
            <input type="text" class="form-control" asp-for="inputtt.Credit" placeholder="1-4">
        </div>
        <div class="col-sm-2"></div>
    </div><br>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-2 ">
            <label asp-for="inputtt.Grade" class="control-label">Grade</label>
        </div>
        <div class="col-sm-7">
            <input type="text" class="form-control" asp-for="inputtt.Grade" placeholder="A,B,C,D">
        </div>
        <div class="col-sm-2"></div>
    </div><br>
    <div class="row">
        <div class="col-lg-5"></div>
        <div class="col-lg-5">
            <input class="btn btn-primary btn-lg" type="submit" name="btn_reg_save" asp-page-handler="Schedule" value="Confirm" />
        </div>
        <div class="col-lg-5"></div>

    </div>
</form>

ContosoUniversity/Pages/Schedule.cshtml
@page
@model ContosoUniversity.Pages.ScheduleModel
@{
    ViewData["Title"] = "Schedule";
}

<h2 >Schedule / Learning Course</h2>

<table class="table table-bordered">
    <tr>
        <th>Full Name</th>
        <th>Course</th>
        <th>Credit</th>
        <th>Enrollment Date</th>
        <th>Grade</th>
        <th></th>
    </tr>
    @foreach (var stu in Model.enrollment)
    {
    <tr>
        <td>@Html.DisplayFor(modelItem => stu.Student.FirstMidName)</td>
        <td>@Html.DisplayFor(modelItem => stu.Student.LastName)</td>
        <td> @Html.DisplayFor(modelItem => stu.Course.Title)</td>
        <td> @Html.DisplayFor(modelItem => stu.Student.EnrollmentDate)</td>
        <td> @Html.DisplayFor(modelItem => stu.Grade)</td>
        <td>
            <a href="#"> Edit</a>
            <a href="#"><u />Delete</a>
        </td>
    </tr>
    }

</table>

ContosoUniversity/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContosoUniversity</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">ContosoUniversity</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/Register">Register</a></li>
                    <li><a asp-page="/Schedule">Schedule/Learning Course</a></li>
                    <li><a asp-page="/Students/Index">Students</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - ContosoUniversity</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>